config/routes.rb
Rails.application.routes.draw do

  get 'home/index'

  devise_for :users
  resources :notes

  root 'home#index'
end

app/models/note.rb
class Note < ActiveRecord::Base
  belongs_to :user

  validates :title, presence: true
  validates :content, presence: true

  scope :sorted, lambda { order('created_at DESC') }
  
  def preview
    self.content.slice(0..100) << '...(read more)'
  end
  
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Associations
  has_many :notes
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :authenticate_user!
  def new
    @note = Note.new
  end

  def index
    @notes = current_user.notes.sorted
  end

  def create
    @note = current_user.notes.new(note_params)

    if @note.save
      redirect_to notes_path, notice: 'Success! You have just written a new note!'
    else
      render :new
    end
  end

  def show
    @note = current_user.notes.find(params[:id])
  end

  def edit
    @note = Note.find(params[:id])
  end

  def update
    @note = Note.find(params[:id])

    if @note.update(note_params)
      flash.notice = "Your note'#{@note.title}' has just been updated!"
      redirect_to @note
    else
      render 'edit'
    end
  end

  def destroy
    @note = Note.find(params[:id])
    @note.destroy

    flash.notice = "Your note has just been trashed!"
    redirect_to notes_path
  end

  private
    def note_params
      params.require(:note).permit(:title, :content)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/views/home/index.html.erb
<h1 class="center">Welcome to Noteful</h1>
<p class="center">Take notes online and access them from anywhere!</p>

<% if current_user %>
  Check out <%= link_to "all your notes", notes_path %>
<% else %>
  <%= link_to "Sign in", new_user_session_path %> or <%= link_to "sign up", new_user_registration_path %> to start creating notes
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Noteful</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <div class='main'>
    <nav class='clearfix'>
      <ul class="pull-right">
        <li><%= link_to "Home", root_path %></li>
        <% if user_signed_in? %>
          <li><%= link_to "Log Out", destroy_user_session_path, method: :delete%></li>
        <% else %>
          <li><%= link_to "Sign Up", new_user_registration_path %></li>
          <li><%= link_to "Log In", new_user_session_path %></li>
        <% end %>
      </ul>
    </nav>
    <div class='content'>
      <p class="flash"><%= flash.notice %></p>
      <%= yield %>
     </div>
  </div>

</body>
</html>

app/views/notes/_form.html.erb
<%= form_for(@note) do |f| %>
  <% if @note.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@note.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @note.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/notes/edit.html.erb
<h1>Edit your note</h1>

<%= render 'form' %>

<%= link_to 'Show', @note %> |
<%= link_to 'Back', notes_path %>

app/views/notes/index.html.erb
<h1 class="center">Welcome to Noteful</h1>
<p class="center">Take notes online and access them from anywhere!</p>

<div class='pull-right'>
  <%= link_to "Add a note", new_note_path %>
</div>

<div>
  <% @notes.each do |note| %>
    <%= div_for note do %>
      <h2><%= note.title %></h2>
      <p><%= note.preview %></p>
      <p><%= link_to 'Show', note_path(note) %> |
        <%= link_to 'Edit', edit_note_path(note) %> |
        <%= link_to 'Destroy', note_path(note), method: :delete, data: { confirm: 'Are you sure?' } %></p>
    <% end %>
  <% end %>
</div>

app/views/notes/new.html.erb
<h1>Write your first note!</h1>

<%= render 'form' %>

<%= link_to 'Back', notes_path %>

app/views/notes/show.html.erb
<div>
  
  <h1><%= @note.title %></h1>
  <p><%= simple_format @note.content %></p>

   <p><%= link_to 'Back', notes_path %> | <%= link_to 'Edit', edit_note_path(@note) %></p>
</div>